[build]
script = "cargo build"
desc = "build the project"

[release]
script  = "cargo build --release"

[clean]
script = "rm -rf target"
desc = "remove cache and outputs"

[meta]
desc = "meta task"
deps = ["clean", "build"]

[deps]
script = "echo asdf"
desc = "task with deps"
deps = ["clean", "build"]

[multi_test]
script = """echo line1
    echo line2
    echo line3
    """
desc = "Test multiline script"
