[run]
script = "cargo run"
desc = "Run with debug logging"
options.environment.RUST_LOG = "mach=debug,info"

[build]
script = "cargo build"
desc = "Build the project"

[release]
script  = "cargo build --release"

[clean]
script = "rm -rf target"
desc = "Remove cache and outputs"

[test]
script = "cargo test"
desc = "Run rust tests"

[check_target_size]
script = "du -d1 -h"
desc = "Check directory sizes of cache dirs"
options.working_directory = "target"

[install]
script = "cargo install --path ."
deps = ["clean"]

