[package]
name = "machfile-cli"
version = "0.2.1"
edition = "2024"
description = "A simple task system, for when a build system is to much"
repository = "https://github.com/machfile/machfile"
license = "MIT"
categories = ["development-tools::build-utils", "command-line-utilities"]

[features]
default = ["complete"]
complete = ["dep:clap_complete"]


[dependencies]
clap = { version = "4.6.2", features = ["cargo", "string"] }
clap_complete = { version = "4.6.7", optional = true }
crossterm = "0.29.0"
env_logger = "0.11.11"
log = "0.4.33"
machfile = { version = "0.3.0", path = "../machfile" }

[[bin]]
name = "mach"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2.2.2"
assert_fs = "1.1.4"
predicates = "3.1.4"
