[package]
name = "machfile"
version = "0.1.0-alpha.1"
edition = "2024"
description = "A simple task system, for when a build system is to much"
repository = "https://github.com/machfile/mach"
license = "MIT"
categories = ["command-line-utilities"]

[dependencies]
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
serde-saphyr = "0.0.21"
