name: Rust

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '.github/workflows/cd.yml'
      - '.github/workflows/release/plz.yml'
      - '.gitignore'
      - 'release-plz.toml'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run clippy
        run: cargo clippy

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run tests
        run: cargo test

  check_fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Check formatting
        run: cargo fmt --check
